[pre-commit]
parallel = true

[pre-commit.commands.lint]
glob = "*.{js,ts,jsx,tsx,vue,json}"
run = "pnpm eslint {staged_files}"

[pre-commit.commands.lychee]
glob = "*.md"
run = "lychee --max-concurrency 3 -v {staged_files}"
